In [9]:
import pandas as pd
from pathlib import Path

current_dir = Path.cwd()
project_root = current_dir.parents[2]

datscan_path = project_root / "DATA_PPMI/Results/DatScan_SBR.csv"
updrs_path = project_root / "DATA_PPMI/Results/MDS_UPDR.csv"
non_motor_path = project_root / "DATA_PPMI/Results/NON_MOTOR_DATA.csv"
subjects_path = project_root / "DATA_PPMI/Results/SUBJECT_CHARACTERISTICS.csv"

# Load the datasets
dat_scan_df = pd.read_csv(datscan_path)
updrs_df = pd.read_csv(updrs_path)
non_motor_df = pd.read_csv(non_motor_path)
subjects_df = pd.read_csv(subjects_path)

In [10]:
subjects_df.head()

   PATNO  ENRLLRRK2  ENRLGBA  SEX  RAWHITE  EDUCYRS EVENT_ID  AGE_AT_VISIT
0   3001          0        0  1.0      1.0     16.0       BL          65.1
1   3001          0        0  1.0      1.0     16.0      V04          66.2
2   3001          0        0  1.0      1.0     16.0      V06          67.3
3   3001          0        0  1.0      1.0     16.0      V08          68.3
4   3001          0        0  1.0      1.0     16.0      V10          69.2

In [11]:
non_motor_df.head()

,PATNO,EVENT_ID,MCAALTTM,MCACUBE,MCACLCKC,MCACLCKN,MCACLCKH,MCALION,MCARHINO,MCACAMEL,...,SLPINJUR,DRMVERBL,DRMFIGHT,DRMUMV,DRMOBJFL,MVAWAKEN,DRMREMEM,SLPDSTRB,STROKE,HETRA
0,3001,BL,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,3001,V04,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,3001,V06,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
3,3001,V08,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,3001,V10,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [12]:
updrs_df.head()

,PATNO,EVENT_ID,NP1COG,NP1HALL,NP1DPRS,NP1ANXS,NP1APAT,NP1DDS,NP1SLPN,NP1SLPD,...,NP3PTRML,NP3KTRMR,NP3KTRML,NP3RTARU,NP3RTALU,NP3RTARL,NP3RTALL,NP3RTALJ,NP3RTCON,NHY
0,3001,BL,0,0,0.0,0.0,0.0,0.0,1.0,2.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3001,V04,1,0,1.0,1.0,1.0,0.0,0.0,2.0,...,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
2,3001,V06,0,0,0.0,0.0,0.0,0.0,1.0,2.0,...,1.0,3.0,2.0,1.0,2.0,0.0,0.0,0.0,2.0,2.0
3,3001,V10,0,0,0.0,1.0,0.0,0.0,1.0,0.0,...,2.0,2.0,2.0,1.0,3.0,0.0,0.0,0.0,3.0,2.0
4,3001,V12,1,0,1.0,1.0,0.0,0.0,1.0,1.0,...,2.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0

In [13]:
dat_scan_df.head()

,PATNO,EVENT_ID,STRIATUM_REF_CWM,CAUDATE_REF_CWM,PUTAMEN_REF_CWM,PRECAUDATE_REF_CWM,POSCAUDATE_REF_CWM,PRECOMMISSURAL_PUTAMEN_REF_CWM,POSCOMMISSURAL_PUTAMEN_REF_CWM,PREDORSALPUTAMEN_REF_CWM,...,CAUDATE_R_REF_CWM,PUTAMEN_R_REF_CWM,PRECAUDATE_R_REF_CWM,POSCAUDATE_R_REF_CWM,PRECOMMISSURAL_PUTAMEN_R_REF_CWM,POSCOMMISSURAL_PUTAMEN_R_REF_CWM,PREDORSALPUTAMEN_R_REF_CWM,PREVENTRALPUTAMEN_R_REF_CWM,POSDORSALPUTAMEN_R_REF_CWM,POSVENTRALPUTAMEN_R_REF_CWM
0,3001,V04,0.64,0.55,0.68,0.69,0.13,0.96,0.45,1.01,...,0.69,0.81,0.86,0.15,1.13,0.54,1.24,0.98,0.57,0.47
1,3001,V06,0.62,0.61,0.59,0.78,0.07,0.96,0.30,0.96,...,0.79,0.67,0.97,0.24,1.12,0.28,1.16,1.08,0.26,0.34
2,3001,V10,0.55,0.50,0.58,0.64,0.07,0.84,0.38,0.83,...,0.58,0.56,0.73,0.12,0.86,0.31,0.85,0.87,0.26,0.44
3,3002,V04,1.02,1.22,0.93,1.45,0.50,1.35,0.59,1.56,...,1.07,0.94,1.30,0.31,1.38,0.55,1.56,1.15,0.60,0.40
4,3002,V06,1.04,1.35,0.86,1.64,0.46,1.27,0.53,1.45,...,1.19,0.80,1.45,0.34,1.16,0.49,1.29,0.99,0.52,0.40

# union

In [14]:
data=subjects_df.merge(non_motor_df, on=['PATNO','EVENT_ID'], how="inner")
data=data.merge(updrs_df, on=['PATNO','EVENT_ID'], how="inner")
data=data.merge(dat_scan_df, on=['PATNO','EVENT_ID'], how="inner")
print(data.shape)
data['PATNO'].nunique()

(2427, 227)

1106