In [1]:
import pandas as pd
from pathlib import Path

current_dir = Path.cwd()

project_root = current_dir.parents[2]
UPDRS1_path = project_root / "DATA_PPMI" / "Motor_MDS_UPDRS" / "MDS-UPDRS_Part_I_02Mar2026.csv"
UPDRS1Q_path = project_root / "DATA_PPMI" / "Motor_MDS_UPDRS" /"MDS-UPDRS_Part_I_Patient_Questionnaire_02Mar2026.csv"
UPDRS2_path = project_root / "DATA_PPMI" / "Motor_MDS_UPDRS" /"MDS_UPDRS_Part_II__Patient_Questionnaire_02Mar2026.csv"
UPDRS3_path = project_root / "DATA_PPMI" / "Motor_MDS_UPDRS" /"MDS-UPDRS_Part_III_02Mar2026.csv"
SEA_path = project_root / "DATA_PPMI" / "Motor_MDS_UPDRS" /"Modified_Schwab___England_Activities_of_Daily_Living_02Mar2026.csv"
subject_path = project_root / "DATA_PPMI/Results/SUBJECT_CHARACTERISTICS.csv"

patnos = pd.read_csv(subject_path)["PATNO"].unique().tolist()
print('Number of unique patients:', len(patnos))

EVENTS=["SC","BL", "V04", "V06", "V08", "V10", "V12"]

Number of unique patients: 7403

# UPDRS1

In [2]:
UPDRS1_data = pd.read_csv(UPDRS1_path)
UPDRS1_data = UPDRS1_data[(UPDRS1_data["PATNO"].isin(patnos))&(UPDRS1_data["EVENT_ID"].isin(EVENTS))&(UPDRS1_data["NUPSOURC"]==1)]

patnos_bl = set(UPDRS1_data.loc[UPDRS1_data['EVENT_ID'] == 'BL', 'PATNO'])
patnos_sc = set(UPDRS1_data.loc[UPDRS1_data['EVENT_ID'] == 'SC', 'PATNO'])

patnos_con_bl_y_sc = patnos_bl.intersection(patnos_sc)

# Eliminar los registros SC solo para esos PATNOs
UPDRS1_data = UPDRS1_data[
    ~((UPDRS1_data['PATNO'].isin(patnos_con_bl_y_sc)) & (UPDRS1_data['EVENT_ID'] == 'SC'))
]

UPDRS1_data['EVENT_ID']= UPDRS1_data['EVENT_ID'].replace({'SC':'BL'})
print('UPDRS 1 shape:', UPDRS1_data.shape)
UPDRS1_data=UPDRS1_data[['PATNO', 'EVENT_ID','NP1COG', 'NP1HALL', 'NP1DPRS', 'NP1ANXS', 'NP1APAT', 'NP1DDS']].copy()
UPDRS1_data = UPDRS1_data.fillna(UPDRS1_data.mode().iloc[0])
print('UPDRS nan', UPDRS1_data.isna().sum().sum())
UPDRS1_data.head()

UPDRS 1 shape: (12490, 15)
UPDRS nan 0

    PATNO EVENT_ID  NP1COG  NP1HALL  NP1DPRS  NP1ANXS  NP1APAT  NP1DDS
9    3001       BL       0        0      0.0      0.0      0.0     0.0
17   3001      V04       1        0      1.0      1.0      1.0     0.0
19   3001      V06       0        0      0.0      0.0      0.0     0.0
21   3001      V08       0        0      0.0      1.0      0.0     0.0
23   3001      V10       0        0      0.0      1.0      0.0     0.0

# UPDRS 1Q

In [3]:
UPDRS1Q_data = pd.read_csv(UPDRS1Q_path)
UPDRS1Q_data


UPDRS1Q_data = UPDRS1Q_data[(UPDRS1Q_data["PATNO"].isin(patnos))&(UPDRS1Q_data["EVENT_ID"].isin(EVENTS))&(UPDRS1Q_data["NUPSOURC"]==1)]

patnos_bl = set(UPDRS1Q_data.loc[UPDRS1Q_data['EVENT_ID'] == 'BL', 'PATNO'])
patnos_sc = set(UPDRS1Q_data.loc[UPDRS1Q_data['EVENT_ID'] == 'SC', 'PATNO'])

patnos_con_bl_y_sc = patnos_bl.intersection(patnos_sc)

# Eliminar los registros SC solo para esos PATNOs
UPDRS1Q_data = UPDRS1Q_data[
    ~((UPDRS1Q_data['PATNO'].isin(patnos_con_bl_y_sc)) & (UPDRS1Q_data['EVENT_ID'] == 'SC'))
]

UPDRS1Q_data['EVENT_ID']= UPDRS1Q_data['EVENT_ID'].replace({'SC':'BL'})
print('UPDRS 1Q shape:', UPDRS1Q_data.shape)

UPDRS1Q_data=UPDRS1Q_data[['PATNO', 'EVENT_ID','NP1SLPN', 'NP1SLPD', 'NP1PAIN', 'NP1URIN', 'NP1CNST', 'NP1LTHD','NP1FATG']].copy()
UPDRS1Q_data = UPDRS1Q_data.fillna(UPDRS1Q_data.mode().iloc[0])
print('UPDRS nan', UPDRS1Q_data.isna().sum().sum())
UPDRS1Q_data.head()

UPDRS 1Q shape: (12790, 16)
UPDRS nan 0

,PATNO,EVENT_ID,NP1SLPN,NP1SLPD,NP1PAIN,NP1URIN,NP1CNST,NP1LTHD,NP1FATG
8,3001,BL,1.0,2.0,0.0,4.0,0.0,0.0,1.0
16,3001,V04,0.0,2.0,0.0,4.0,0.0,0.0,2.0
18,3001,V06,1.0,2.0,1.0,4.0,0.0,0.0,1.0
20,3001,V08,0.0,2.0,1.0,4.0,1.0,1.0,1.0
22,3001,V10,1.0,0.0,0.0,4.0,1.0,0.0,0.0

# UPDRS 2

In [4]:
UPDRS2_data = pd.read_csv(UPDRS2_path)
UPDRS2_data

UPDRS2_data = UPDRS2_data[(UPDRS2_data["PATNO"].isin(patnos))&(UPDRS2_data["EVENT_ID"].isin(EVENTS))&(UPDRS2_data["NUPSOURC"]==1)]

patnos_bl = set(UPDRS2_data.loc[UPDRS2_data['EVENT_ID'] == 'BL', 'PATNO'])
patnos_sc = set(UPDRS2_data.loc[UPDRS2_data['EVENT_ID'] == 'SC', 'PATNO'])

patnos_con_bl_y_sc = patnos_bl.intersection(patnos_sc)

# Eliminar los registros SC solo para esos PATNOs
UPDRS2_data = UPDRS2_data[
    ~((UPDRS2_data['PATNO'].isin(patnos_con_bl_y_sc)) & (UPDRS2_data['EVENT_ID'] == 'SC'))
]

UPDRS2_data['EVENT_ID']= UPDRS2_data['EVENT_ID'].replace({'SC':'BL'})
print('UPDRS 2 shape:', UPDRS2_data.shape)

UPDRS2_data=UPDRS2_data[['PATNO', 'EVENT_ID','NP2SPCH', 'NP2SALV', 'NP2SWAL', 'NP2EAT', 'NP2DRES', 'NP2HYGN',
       'NP2HWRT', 'NP2HOBB', 'NP2TURN', 'NP2TRMR', 'NP2RISE', 'NP2WALK',
       'NP2FREZ']].copy()

UPDRS2_data = UPDRS2_data.fillna(UPDRS2_data.mode().iloc[0])
print('UPDRS 2 nan', UPDRS2_data.isna().sum().sum())

UPDRS2_data.head()

UPDRS 2 shape: (12800, 22)
UPDRS 2 nan 0

,PATNO,EVENT_ID,NP2SPCH,NP2SALV,NP2SWAL,NP2EAT,NP2DRES,NP2HYGN,NP2HWRT,NP2HOBB,NP2TURN,NP2TRMR,NP2RISE,NP2WALK,NP2FREZ
8,3001,BL,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
16,3001,V04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0
18,3001,V06,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
20,3001,V08,0.0,0.0,0.0,1.0,1.0,0.0,2.0,0.0,0.0,1.0,1.0,0.0,0.0
22,3001,V10,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

# UPDRS 3

In [5]:
import pandas as pd

# --- Cargar y filtrar ---
UPDRS3_data = pd.read_csv(UPDRS3_path, low_memory=False)

UPDRS3_data = UPDRS3_data[
    (UPDRS3_data['PDTRTMNT'].isin([0, 1]) | UPDRS3_data['PDTRTMNT'].isna()) &
    ((UPDRS3_data['PDSTATE'] == 'OFF') | UPDRS3_data['PDSTATE'].isna())
]

UPDRS3_data = UPDRS3_data[
    (UPDRS3_data["PATNO"].isin(patnos)) &
    (UPDRS3_data["EVENT_ID"].isin(EVENTS))
].copy()

cols_imputar = [
    'NP3SPCH', 'NP3FACXP', 'NP3RIGN', 'NP3RIGRU',
    'NP3RIGLU', 'NP3RIGRL', 'NP3RIGLL', 'NP3FTAPR', 'NP3FTAPL',
    'NP3HMOVR', 'NP3HMOVL', 'NP3PRSPR', 'NP3PRSPL', 'NP3TTAPR',
    'NP3TTAPL', 'NP3LGAGR', 'NP3LGAGL', 'NP3RISNG', 'NP3GAIT',
    'NP3FRZGT', 'NP3PSTBL', 'NP3POSTR', 'NP3BRADY', 'NP3PTRMR',
    'NP3PTRML', 'NP3KTRMR', 'NP3KTRML', 'NP3RTARU', 'NP3RTALU',
    'NP3RTARL', 'NP3RTALL', 'NP3RTALJ', 'NP3RTCON', 'NHY'
]

UPDRS3_data = UPDRS3_data[['PATNO', 'EVENT_ID'] + cols_imputar].copy()

# --- Si un paciente tiene BL y SC, borrar SC y convertir SC->BL ---
patnos_bl = set(UPDRS3_data.loc[UPDRS3_data['EVENT_ID'] == 'BL', 'PATNO'])
patnos_sc = set(UPDRS3_data.loc[UPDRS3_data['EVENT_ID'] == 'SC', 'PATNO'])
patnos_con_bl_y_sc = patnos_bl.intersection(patnos_sc)

UPDRS3_data = UPDRS3_data[
    ~((UPDRS3_data['PATNO'].isin(patnos_con_bl_y_sc)) & (UPDRS3_data['EVENT_ID'] == 'SC'))
].copy()

UPDRS3_data['EVENT_ID'] = UPDRS3_data['EVENT_ID'].replace({'SC': 'BL'})

UPDRS3_data.head()

,PATNO,EVENT_ID,NP3SPCH,NP3FACXP,NP3RIGN,NP3RIGRU,NP3RIGLU,NP3RIGRL,NP3RIGLL,NP3FTAPR,...,NP3PTRML,NP3KTRMR,NP3KTRML,NP3RTARU,NP3RTALU,NP3RTARL,NP3RTALL,NP3RTALJ,NP3RTCON,NHY
9,3001,BL,1.0,1.0,0.0,2.0,0.0,0.0,0.0,2.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14,3001,V04,1.0,1.0,0.0,2.0,1.0,0.0,0.0,1.0,...,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
16,3001,V06,2.0,2.0,1.0,3.0,2.0,2.0,2.0,1.0,...,1.0,3.0,2.0,1.0,2.0,0.0,0.0,0.0,2.0,2.0
20,3001,V10,1.0,1.0,0.0,2.0,1.0,1.0,0.0,2.0,...,2.0,2.0,2.0,1.0,3.0,0.0,0.0,0.0,3.0,2.0
23,3001,V12,1.0,1.0,0.0,3.0,2.0,1.0,1.0,2.0,...,2.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,2.0

# SEAL

In [6]:
SEAL_data = pd.read_csv(SEA_path)
SEAL_data = SEAL_data[(SEAL_data["PATNO"].isin(patnos))&(SEAL_data["EVENT_ID"].isin(EVENTS))]
SEAL_data=SEAL_data[['PATNO', 'EVENT_ID','MSEADLG']].copy()
patnos_bl = set(SEAL_data.loc[SEAL_data['EVENT_ID'] == 'BL', 'PATNO'])
patnos_sc = set(SEAL_data.loc[SEAL_data['EVENT_ID'] == 'SC', 'PATNO'])
patnos_con_bl_y_sc = patnos_bl.intersection(patnos_sc)
# Eliminar los registros SC solo para esos PATNOs
SEAL_data = SEAL_data[
    ~((SEAL_data['PATNO'].isin(patnos_con_bl_y_sc)) & (SEAL_data['EVENT_ID'] == 'SC'))
]
SEAL_data['EVENT_ID']= SEAL_data['EVENT_ID'].replace({'SC':'BL'})
print('SEAL shape:', SEAL_data.shape)
SEAL_data

SEAL shape: (13329, 3)

        PATNO EVENT_ID  MSEADLG
1        3001       BL     95.0
9        3001      V04     95.0
11       3001      V06     95.0
13       3001      V08     95.0
15       3001      V10     90.0
...       ...      ...      ...
30081  546130       BL    100.0
30082  549230       BL    100.0
30083  550662       BL    100.0
30084  571000       BL     85.0
30085  572491       BL    100.0

[13329 rows x 3 columns]

# FINAL DATA UNION

In [7]:
data=UPDRS1_data.merge(UPDRS1Q_data, on=['PATNO', 'EVENT_ID'], how='outer')
data=data.merge(UPDRS2_data, on=['PATNO', 'EVENT_ID'], how='outer')
data=data.merge(SEAL_data, on=['PATNO', 'EVENT_ID'], how='outer')
data=data.merge(UPDRS3_data, on=['PATNO', 'EVENT_ID'], how='outer')

print('Merged data shape:', data.shape)
data.to_csv(project_root / "DATA_PPMI/Results/MDS_UPDR.csv", index=False)
data.head()

Merged data shape: (13389, 63)

,PATNO,EVENT_ID,NP1COG,NP1HALL,NP1DPRS,NP1ANXS,NP1APAT,NP1DDS,NP1SLPN,NP1SLPD,...,NP3PTRML,NP3KTRMR,NP3KTRML,NP3RTARU,NP3RTALU,NP3RTARL,NP3RTALL,NP3RTALJ,NP3RTCON,NHY
0,3001,BL,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,...,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3001,V04,1.0,0.0,1.0,1.0,1.0,0.0,0.0,2.0,...,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
2,3001,V06,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,...,1.0,3.0,2.0,1.0,2.0,0.0,0.0,0.0,2.0,2.0
3,3001,V08,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3001,V10,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,2.0,2.0,2.0,1.0,3.0,0.0,0.0,0.0,3.0,2.0

In [8]:
data['EVENT_ID'].value_counts()

EVENT_ID
BL     4498
V04    3197
V06    2350
V08    1475
V10    1028
V12     841
Name: count, dtype: int64