In [46]:
import pandas as pd
from pathlib import Path

current_dir = Path.cwd()
project_root = current_dir.parents[2]

MoCA_path = project_root /'DATA_PPMI/Non_Motor/Montreal_Cognitive_Assessment__MoCA__02Mar2026.csv'
SCOPA_path = project_root /'DATA_PPMI/Non_Motor/SCOPA-AUT_02Mar2026.csv'
GDS_path = project_root /'DATA_PPMI/Non_Motor/Neurobehavioral/Geriatric_Depression_Scale__Short_Version__02Mar2026.csv'
STAI_path = project_root /'DATA_PPMI/Non_Motor/Neurobehavioral/State-Trait_Anxiety_Inventory_02Mar2026.csv'
ESS_path = project_root /'DATA_PPMI/Non_Motor/Sleep_Disorder/Epworth_Sleepiness_Scale_02Mar2026.csv'
RSBQ_path = project_root /'DATA_PPMI/Non_Motor/Sleep_Disorder/REM_Sleep_Behavior_Disorder_Questionnaire_02Mar2026.csv'
subject_path = project_root / "DATA_PPMI/Results/SUBJECT_CHARACTERISTICS.csv"

patnos = pd.read_csv(subject_path)["PATNO"].unique().tolist()
print('Number of unique patients:', len(patnos))

EVENTS=["SC","BL", "V04", "V06", "V08", "V10", "V12"]

Number of unique patients: 7403

# MoCa

In [47]:
moca_data = pd.read_csv(MoCA_path)
moca_data = moca_data[moca_data['PATNO'].isin(patnos) & moca_data['EVENT_ID'].isin(EVENTS)]

patnos_bl = set(moca_data.loc[moca_data['EVENT_ID'] == 'BL', 'PATNO'])
patnos_sc = set(moca_data.loc[moca_data['EVENT_ID'] == 'SC', 'PATNO'])

patnos_con_bl_y_sc = patnos_bl.intersection(patnos_sc)

# Eliminar los registros SC solo para esos PATNOs
moca_data = moca_data[
    ~((moca_data['PATNO'].isin(patnos_con_bl_y_sc)) & (moca_data['EVENT_ID'] == 'SC'))
]

moca_data['EVENT_ID']= moca_data['EVENT_ID'].replace({'SC':'BL'})
print('moca_data shape:', moca_data.shape)
moca_data=moca_data[['PATNO','EVENT_ID','MCAALTTM','MCACUBE', 'MCACLCKC', 'MCACLCKN', 'MCACLCKH', 'MCALION', 'MCARHINO',
                        'MCACAMEL', 'MCAFDS', 'MCABDS', 'MCAVIGIL', 'MCASER7', 'MCASNTNC',
                        'MCAVFNUM', 'MCAVF', 'MCAABSTR', 'MCAREC1', 'MCAREC2', 'MCAREC3',
                        'MCAREC4', 'MCAREC5', 'MCADATE', 'MCAMONTH', 'MCAYR', 'MCADAY',
                        'MCAPLACE', 'MCACITY']].copy()
moca_data = moca_data.fillna(moca_data.mode().iloc[0])
print('moca is na:', moca_data.isna().sum().sum())
moca_data

moca_data shape: (13253, 35)
moca is na: 0

,PATNO,EVENT_ID,MCAALTTM,MCACUBE,MCACLCKC,MCACLCKN,MCACLCKH,MCALION,MCARHINO,MCACAMEL,...,MCAREC2,MCAREC3,MCAREC4,MCAREC5,MCADATE,MCAMONTH,MCAYR,MCADAY,MCAPLACE,MCACITY
9,3001,BL,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
10,3001,V04,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
11,3001,V06,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
12,3001,V08,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
13,3001,V10,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18633,543866,BL,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
18634,549230,BL,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
18635,550662,BL,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,...,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
18636,571000,BL,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
18637,572491,BL,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

# SCOPA

In [48]:
scopa_data = pd.read_csv(SCOPA_path)
print(scopa_data.columns)
scopa_data = scopa_data[scopa_data['PATNO'].isin(patnos) & scopa_data['EVENT_ID'].isin(EVENTS)&(scopa_data['PTCGBOTH']==1)]
patnos_bl = set(scopa_data.loc[scopa_data['EVENT_ID'] == 'BL', 'PATNO'])
patnos_sc = set(scopa_data.loc[scopa_data['EVENT_ID'] == 'SC', 'PATNO'])
patnos_con_bl_y_sc = patnos_bl.intersection(patnos_sc)
scopa_data = scopa_data[
    ~((scopa_data['PATNO'].isin(patnos_con_bl_y_sc)) & (scopa_data['EVENT_ID'] == 'SC'))
]
scopa_data['EVENT_ID']= scopa_data['EVENT_ID'].replace({'SC':'BL'})
print('scopa_data is na:', scopa_data.isna().sum().sum())
print('scopa_data shape:', scopa_data.shape)
scopa_data=scopa_data[['PATNO','EVENT_ID','SCAU1', 'SCAU2', 'SCAU3', 'SCAU4', 'SCAU5', 'SCAU6', 'SCAU7', 'SCAU8',
                        'SCAU9', 'SCAU10', 'SCAU11', 'SCAU12', 'SCAU13', 'SCAU14', 'SCAU15',
                        'SCAU16', 'SCAU17', 'SCAU18', 'SCAU19', 'SCAU20', 'SCAU21']].copy()

scopa_data = scopa_data.fillna(scopa_data.mode().iloc[0])
print('scopa_data is na:', scopa_data.isna().sum().sum())
scopa_data.head()

Index(['REC_ID', 'PATNO', 'EVENT_ID', 'PAG_NAME', 'INFODT', 'PTCGBOTH',
       'SCAU1', 'SCAU2', 'SCAU3', 'SCAU4', 'SCAU5', 'SCAU6', 'SCAU7', 'SCAU8',
       'SCAU9', 'SCAU10', 'SCAU11', 'SCAU12', 'SCAU13', 'SCAU14', 'SCAU15',
       'SCAU16', 'SCAU17', 'SCAU18', 'SCAU19', 'SCAU20', 'SCAU21', 'SCAU22',
       'SCAU23', 'SCAU23A', 'SCAU23AT', 'SCAU24', 'SCAU25', 'SCAU26A',
       'SCAU26AT', 'SCAU26B', 'SCAU26BT', 'SCAU26C', 'SCAU26CT', 'SCAU26D',
       'SCAU26DT', 'ORIG_ENTRY', 'LAST_UPDATE'],
      dtype='str')
scopa_data is na: 70085
scopa_data shape: (12580, 43)
scopa_data is na: 0

,PATNO,EVENT_ID,SCAU1,SCAU2,SCAU3,SCAU4,SCAU5,SCAU6,SCAU7,SCAU8,...,SCAU12,SCAU13,SCAU14,SCAU15,SCAU16,SCAU17,SCAU18,SCAU19,SCAU20,SCAU21
9,3001,BL,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,3001,V04,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,...,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
12,3001,V06,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
13,3001,V08,1.0,1.0,1.0,1.0,1.0,1.0,0.0,2.0,...,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
14,3001,V10,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

# GDS

In [49]:
gds_data = pd.read_csv(GDS_path)
gds_data = gds_data[gds_data['PATNO'].isin(patnos) & gds_data['EVENT_ID'].isin(EVENTS)]
patnos_bl = set(gds_data.loc[gds_data['EVENT_ID'] == 'BL', 'PATNO'])
patnos_sc = set(gds_data.loc[gds_data['EVENT_ID'] == 'SC', 'PATNO'])
patnos_con_bl_y_sc = patnos_bl.intersection(patnos_sc)
gds_data = gds_data[
    ~((gds_data['PATNO'].isin(patnos_con_bl_y_sc)) & (gds_data['EVENT_ID'] == 'SC'))
]
gds_data['EVENT_ID']= gds_data['EVENT_ID'].replace({'SC':'BL'})
gds_data = gds_data.fillna(gds_data.mode().iloc[0])
print('gds_data is na:', gds_data.isna().sum().sum())
print('gds_data shape:', gds_data.shape)
gds_data=gds_data[['PATNO','EVENT_ID','GDSSATIS',
       'GDSDROPD', 'GDSEMPTY', 'GDSBORED', 'GDSGSPIR', 'GDSAFRAD', 'GDSHAPPY',
       'GDSHLPLS', 'GDSHOME', 'GDSMEMRY', 'GDSALIVE', 'GDSWRTLS', 'GDSENRGY',
       'GDSHOPLS', 'GDSBETER']].copy()

gds_data.head()

gds_data is na: 0
gds_data shape: (13216, 22)

,PATNO,EVENT_ID,GDSSATIS,GDSDROPD,GDSEMPTY,GDSBORED,GDSGSPIR,GDSAFRAD,GDSHAPPY,GDSHLPLS,GDSHOME,GDSMEMRY,GDSALIVE,GDSWRTLS,GDSENRGY,GDSHOPLS,GDSBETER
9,3001,BL,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
11,3001,V04,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
12,3001,V06,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
13,3001,V08,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
14,3001,V10,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0

# STAI

In [50]:
stai_data = pd.read_csv(STAI_path)
stai_data = stai_data[stai_data['PATNO'].isin(patnos) & stai_data['EVENT_ID'].isin(EVENTS)]
patnos_bl = set(stai_data.loc[stai_data['EVENT_ID'] == 'BL', 'PATNO'])
patnos_sc = set(stai_data.loc[stai_data['EVENT_ID'] == 'SC', 'PATNO'])
patnos_con_bl_y_sc = patnos_bl.intersection(patnos_sc)
stai_data = stai_data[
    ~((stai_data['PATNO'].isin(patnos_con_bl_y_sc)) & (stai_data['EVENT_ID'] == 'SC'))
]
stai_data['EVENT_ID']= stai_data['EVENT_ID'].replace({'SC':'BL'})
stai_data = stai_data.fillna(stai_data.mode().iloc[0])
print('stai_data is na:', stai_data.isna().sum().sum())
print('stai_data shape:', stai_data.shape)
stai_data=stai_data[['PATNO','EVENT_ID',"STAIAD1","STAIAD2","STAIAD3","STAIAD4","STAIAD5","STAIAD6","STAIAD7","STAIAD8","STAIAD9",
    "STAIAD10","STAIAD11","STAIAD12","STAIAD13","STAIAD14","STAIAD15","STAIAD16","STAIAD17",
    "STAIAD18","STAIAD19","STAIAD20","STAIAD21","STAIAD22","STAIAD23","STAIAD24","STAIAD25",
    "STAIAD26","STAIAD27","STAIAD28","STAIAD29","STAIAD30","STAIAD31","STAIAD32","STAIAD33",
    "STAIAD34","STAIAD35","STAIAD36","STAIAD37","STAIAD38","STAIAD39","STAIAD40"]].copy()
stai_data.head()

stai_data is na: 0
stai_data shape: (13191, 47)

,PATNO,EVENT_ID,STAIAD1,STAIAD2,STAIAD3,STAIAD4,STAIAD5,STAIAD6,STAIAD7,STAIAD8,...,STAIAD31,STAIAD32,STAIAD33,STAIAD34,STAIAD35,STAIAD36,STAIAD37,STAIAD38,STAIAD39,STAIAD40
9,3001,BL,4.0,4.0,2.0,1.0,1.0,1.0,1.0,4.0,...,1.0,2.0,4.0,2.0,1.0,4.0,1.0,1.0,4.0,1.0
11,3001,V04,4.0,4.0,4.0,4.0,4.0,1.0,1.0,3.0,...,2.0,2.0,3.0,2.0,2.0,3.0,1.0,2.0,4.0,2.0
12,3001,V06,4.0,4.0,1.0,1.0,4.0,1.0,1.0,4.0,...,2.0,2.0,4.0,1.0,2.0,3.0,2.0,2.0,4.0,2.0
13,3001,V08,4.0,4.0,1.0,1.0,4.0,4.0,1.0,3.0,...,2.0,2.0,4.0,3.0,2.0,4.0,1.0,2.0,4.0,1.0
14,3001,V10,4.0,4.0,1.0,1.0,4.0,1.0,1.0,4.0,...,2.0,2.0,4.0,2.0,2.0,3.0,2.0,2.0,4.0,1.0

# ESS

In [51]:
ess_data = pd.read_csv(ESS_path)
ess_data = ess_data[ess_data['PATNO'].isin(patnos) & ess_data['EVENT_ID'].isin(EVENTS)& (ess_data['PTCGBOTH']==1)]
patnos_bl = set(ess_data.loc[ess_data['EVENT_ID'] == 'BL', 'PATNO'])
patnos_sc = set(ess_data.loc[ess_data['EVENT_ID'] == 'SC', 'PATNO'])
patnos_con_bl_y_sc = patnos_bl.intersection(patnos_sc)
ess_data = ess_data[
    ~((ess_data['PATNO'].isin(patnos_con_bl_y_sc)) & (ess_data['EVENT_ID'] == 'SC'))
]
ess_data['EVENT_ID']= ess_data['EVENT_ID'].replace({'SC':'BL'})

ess_data = ess_data.fillna(ess_data.mode().iloc[0])
print('ess_data is na:', ess_data.isna().sum().sum())
print('ess_data shape:', ess_data.shape)
ess_data=ess_data[['PATNO','EVENT_ID','ESS1', 'ESS2', 'ESS3', 'ESS4', 'ESS5', 'ESS6', 'ESS7', 'ESS8']].copy()
ess_data.head()

ess_data is na: 0
ess_data shape: (12583, 16)

    PATNO EVENT_ID  ESS1  ESS2  ESS3  ESS4  ESS5  ESS6  ESS7  ESS8
9    3001       BL     1   3.0   0.0   0.0   2.0   0.0   0.0   0.0
11   3001      V04     0   1.0   0.0   0.0   2.0   0.0   0.0   0.0
12   3001      V06     1   2.0   1.0   1.0   2.0   0.0   0.0   0.0
13   3001      V08     1   2.0   0.0   1.0   1.0   0.0   0.0   0.0
14   3001      V10     1   2.0   1.0   0.0   2.0   0.0   0.0   0.0

# RSBQ

In [52]:
rsbq_data = pd.read_csv(RSBQ_path)
rsbq_data = rsbq_data[rsbq_data['PATNO'].isin(patnos) & rsbq_data['EVENT_ID'].isin(EVENTS)& (rsbq_data['PTCGBOTH']==1)]
patnos_bl = set(rsbq_data.loc[rsbq_data['EVENT_ID'] == 'BL', 'PATNO'])
patnos_sc = set(rsbq_data.loc[rsbq_data['EVENT_ID'] == 'SC', 'PATNO'])
patnos_con_bl_y_sc = patnos_bl.intersection(patnos_sc)
rsbq_data = rsbq_data[
    ~((rsbq_data['PATNO'].isin(patnos_con_bl_y_sc)) & (rsbq_data['EVENT_ID'] == 'SC'))
]
rsbq_data['EVENT_ID']= rsbq_data['EVENT_ID'].replace({'SC':'BL'})
rsbq_data = rsbq_data.fillna(rsbq_data.mode().iloc[0])
print('rsbq_data is na:', rsbq_data.isna().sum().sum())
print('rsbq_data shape:', rsbq_data.shape)
rsbq_data=rsbq_data[['PATNO','EVENT_ID','DRMVIVID', 'DRMAGRAC', 'DRMNOCTB', 'SLPLMBMV', 'SLPINJUR', 'DRMVERBL',
       'DRMFIGHT', 'DRMUMV', 'DRMOBJFL', 'MVAWAKEN', 'DRMREMEM', 'SLPDSTRB',
       'STROKE', 'HETRA']].copy()

rsbq_data.head()

rsbq_data is na: 0
rsbq_data shape: (12506, 29)

,PATNO,EVENT_ID,DRMVIVID,DRMAGRAC,DRMNOCTB,SLPLMBMV,SLPINJUR,DRMVERBL,DRMFIGHT,DRMUMV,DRMOBJFL,MVAWAKEN,DRMREMEM,SLPDSTRB,STROKE,HETRA
9,3001,BL,1.0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
11,3001,V04,1.0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
12,3001,V06,1.0,1,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
13,3001,V08,1.0,0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
14,3001,V10,1.0,0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

# DATA UNION

In [53]:
data=moca_data.merge(scopa_data, on=['PATNO', 'EVENT_ID'], how='outer')
data=data.merge(gds_data, on=['PATNO', 'EVENT_ID'], how='outer')
data=data.merge(stai_data, on=['PATNO', 'EVENT_ID'], how='outer')
data=data.merge(ess_data, on=['PATNO', 'EVENT_ID'], how='outer')
data=data.merge(rsbq_data, on=['PATNO', 'EVENT_ID'], how='outer')
print('data shape:', data.shape)
print('data is na:', data.isna().sum().sum())

non_motor_path = project_root / "DATA_PPMI/Results/NON_MOTOR_DATA.csv"
data.to_csv(non_motor_path, index=False)
data.head()

data shape: (13571, 127)
data is na: 72736

,PATNO,EVENT_ID,MCAALTTM,MCACUBE,MCACLCKC,MCACLCKN,MCACLCKH,MCALION,MCARHINO,MCACAMEL,...,SLPINJUR,DRMVERBL,DRMFIGHT,DRMUMV,DRMOBJFL,MVAWAKEN,DRMREMEM,SLPDSTRB,STROKE,HETRA
0,3001,BL,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,3001,V04,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,3001,V06,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
3,3001,V08,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,3001,V10,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [54]:
data['EVENT_ID'].value_counts()

EVENT_ID
BL     4701
V04    3192
V06    2347
V08    1473
V10    1022
V12     836
Name: count, dtype: int64